name: CI/CD with Self Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install --user -r requirements.txt

      - name: Stop existing app
        run: |
          pkill -f app.py || true

      - name: Start app
        run: |
          nohup python3 app.py > output.log 2>&1 &
